### ISSUE TITLE
Please add these links for 2019

### ISSUE THREAD

**Issue by hrstoyanov** [arranger1044/awesome-spn#18]
- [Deep Convolutional Sum-Product Networks for
Probabilistic Image Representations](https://arxiv.org/pdf/1902.06155.pdf)

- [Deep Convolutional Sum-Product Networks](https://www.aaai.org/Papers/AAAI/2019/AAAI-ButzC.3622.pdf)

- [SPFlow: An Easy and Extensible Library for Deep Probabilistic Learning using Sum-Product Networks](https://arxiv.org/abs/1901.03704)

**Comment by hayesall** [comment]
Noticed the AAAI2019 DCSPN was missing yesterday. I'll submit a pull request in an hour or so!
