### ISSUE TITLE
recommendation for newbie

### ISSUE THREAD

**Issue by pribadihcr** [arranger1044/awesome-spn#2]
Hi @arranger1044,

I am interesting and new in SPN. Is there a recommendation open source code for me to begin with. 

Thanks,
rchip

**Comment by arranger1044** [comment]
Hi @pribadihcr ,
have you taken a look at the repos listed in the code section?
What is your background and what are the languages you are familiar with?

**Comment by pribadihcr** [comment]
Hi @arranger1044 

Suppose I want to try  image classification in python. Do I need to initialize the structure SPN first, or just feed the data/feature and get the prediction result?.

**Comment by arranger1044** [comment]
You need to either provide a built network (by crafting it by hand like in [Gens2012] or automatically determining a fixed structure like in [Poon2011]) and then go with weight learning, or start with structure learning.
Depending on your domain dimensionality, one approach of the other may contain some caveat.

Have a look at the seminal paper [Poon2011]'s code whose network structure is crafted for images.
