### ISSUE TITLE
Vectorized algorithms?

### ISSUE THREAD

**Issue by hrstoyanov** [arranger1044/awesome-spn#3]
Hi all,
I looked at the Java and C++ source code for SPN, and the graph structures/classes won't be very useful when using a GPU. Has anyone tried vectorizing the SPN algorithms?

Thanks.

**Comment by arranger1044** [comment]
Hi, have a look at the reparametrization of SPNs as Multi-layer Perceptrons in [Vergari2016a].
This matrix representation has been implemented in `spyn-repr` in theano

**Comment by hrstoyanov** [comment]
Thank you, will look!
